### ISSUE TITLE
Anyone has working code of "Fair search Engine" with GUI

### ISSUE THREAD

**Issue by aravindh-c** [DTL-FAIRData/FAIRSearchEngine#1]
Anyone has working code of "Fair search Engine" with GUI.  I don't think the current code will work, but I've seen a youtube video in which end-to-end demo of Data Fair tools were used.
Link : https://www.youtube.com/watch?v=c5EgIQMn1t4
Can anyone help me to install "Fair search engine" locally.

**Comment by kburger** [comment]
Hi @aravindh-c. The only working example we have is the docker image, available at https://hub.docker.com/repository/docker/dtlfair/search.

You can use this docker-compose snippet to get it up and running:
```
search:
  image: dtlfair/search:develop
  ports:
    - "127.0.0.1:80:80"
    - "127.0.0.1:8080:8080"
    - "127.0.0.1:9200:9200"
  environment:
    - "ES_URL=http://localhost/searchserver"
```

As a side note, please keep in mind this is a proof of concept project. There has not been any maintenance or development on it for a couple of years. Happy to discuss anything around the search engine though, to see if we can fit it in existing initiatives.
